/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.granpet.Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnCadastros = new javax.swing.JMenu();
        jmnCadastroCliente = new javax.swing.JMenuItem();
        jmnCadastroProduto = new javax.swing.JMenuItem();
        jmnCadastroServico = new javax.swing.JMenuItem();
        jmnCadastroUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmnCadastroSair = new javax.swing.JMenuItem();
        jmnRelatorios = new javax.swing.JMenu();
        jmnRelatorioClientes = new javax.swing.JMenuItem();
        jmnRelatorioProdutos = new javax.swing.JMenuItem();
        jmnRelatorioServicos = new javax.swing.JMenuItem();
        jmnRelatorioUsuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmnFerramentaCalculadora = new javax.swing.JMenuItem();
        jmnFerramentaAgenda = new javax.swing.JMenuItem();
        jmnFerramentaEntradas = new javax.swing.JMenuItem();
        jmnFerramentaSaidas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Granpet");
        setBackground(new java.awt.Color(255, 255, 255));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/granpet/Imagens/dogico.png"))); // NOI18N
        btnCliente.setToolTipText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/granpet/Imagens/entrada.png"))); // NOI18N
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/granpet/Imagens/product.png"))); // NOI18N
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("jLabel2");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jmnCadastros.setText("Cadastros");

        jmnCadastroCliente.setText("Cliente");
        jmnCadastros.add(jmnCadastroCliente);

        jmnCadastroProduto.setText("Produto");
        jmnCadastros.add(jmnCadastroProduto);

        jmnCadastroServico.setText("Serviço");
        jmnCadastros.add(jmnCadastroServico);

        jmnCadastroUsuario.setText("Usuário");
        jmnCadastros.add(jmnCadastroUsuario);
        jmnCadastros.add(jSeparator1);

        jmnCadastroSair.setText("Sair");
        jmnCadastroSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastroSairActionPerformed(evt);
            }
        });
        jmnCadastros.add(jmnCadastroSair);

        jMenuBar1.add(jmnCadastros);

        jmnRelatorios.setText("Relatórios");

        jmnRelatorioClientes.setText("Clientes");
        jmnRelatorios.add(jmnRelatorioClientes);

        jmnRelatorioProdutos.setText("Produtos");
        jmnRelatorios.add(jmnRelatorioProdutos);

        jmnRelatorioServicos.setText("Serviços");
        jmnRelatorios.add(jmnRelatorioServicos);

        jmnRelatorioUsuario.setText("Usuários");
        jmnRelatorios.add(jmnRelatorioUsuario);

        jMenuBar1.add(jmnRelatorios);

        jMenu1.setText("Ferramentas");

        jmnFerramentaCalculadora.setText("Calculadora");
        jMenu1.add(jmnFerramentaCalculadora);

        jmnFerramentaAgenda.setText("Agenda");
        jMenu1.add(jmnFerramentaAgenda);

        jmnFerramentaEntradas.setText("Entradas");
        jMenu1.add(jmnFerramentaEntradas);

        jmnFerramentaSaidas.setText("Saídas");
        jMenu1.add(jmnFerramentaSaidas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktop))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastraCliente tcc = new TelaCadastraCliente();
        desktop.add(tcc);
        tcc.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        TelaCadastroProdutos tcp = new TelaCadastroProdutos();
        desktop.add(tcp);
        tcp.setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void jmnCadastroSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastroSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Sair do sistema?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(sair);
        }
    }//GEN-LAST:event_jmnCadastroSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnServicos;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmnCadastroCliente;
    private javax.swing.JMenuItem jmnCadastroProduto;
    private javax.swing.JMenuItem jmnCadastroSair;
    private javax.swing.JMenuItem jmnCadastroServico;
    private javax.swing.JMenuItem jmnCadastroUsuario;
    private javax.swing.JMenu jmnCadastros;
    private javax.swing.JMenuItem jmnFerramentaAgenda;
    private javax.swing.JMenuItem jmnFerramentaCalculadora;
    private javax.swing.JMenuItem jmnFerramentaEntradas;
    private javax.swing.JMenuItem jmnFerramentaSaidas;
    private javax.swing.JMenuItem jmnRelatorioClientes;
    private javax.swing.JMenuItem jmnRelatorioProdutos;
    private javax.swing.JMenuItem jmnRelatorioServicos;
    private javax.swing.JMenuItem jmnRelatorioUsuario;
    private javax.swing.JMenu jmnRelatorios;
    private javax.swing.JLabel lblData;
    public javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
