/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.granpet.Telas;

import com.granpet.aplicacoes.FormataData;
import com.granpet.aplicacoes.FormataNumeros;
import com.granpet.classes.Produto;
import com.granpet.funcoes.FuncoesProduto;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class TelaCadastroProdutos extends javax.swing.JInternalFrame {

    FormataNumeros fn = new FormataNumeros();
    FormataData fd = new FormataData();
    FuncoesProduto fp = new FuncoesProduto();
    DecimalFormat df = new DecimalFormat("#.00");
    Produto produto = new Produto();

    /**
     * Creates new form TelaCadastroProdutos
     */
    public TelaCadastroProdutos() {
        initComponents();
        btnExcluir.setEnabled(false);
        btnSalvar.setText("Novo");
        txtMarca.setEnabled(false);
        txtCategoria.setEnabled(false);
        txtValidade.setEnabled(false);
        txtQTD.setEnabled(false);
        txtValorCompra.setEnabled(false);
        txtLucro.setEnabled(false);
        txtValorVenda.setEnabled(false);
        txtValorVenda.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtQTD = new javax.swing.JTextField();
        txtLucro = new javax.swing.JTextField();
        txtValidade = new javax.swing.JFormattedTextField();
        txtValorCompra = new javax.swing.JFormattedTextField();
        txtValorVenda = new javax.swing.JFormattedTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtos");

        jScrollPane1.setViewportView(tblProdutos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Produto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Categoria:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Validade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Qtd:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Valor Compra:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lucro:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Valor Venda:");

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setPreferredSize(new java.awt.Dimension(90, 33));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 33));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(90, 33));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(90, 33));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMarca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtQTD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtLucro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLucroFocusLost(evt);
            }
        });

        txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtValidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtValorCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValorCompra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtValorVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtValorVenda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtMarca)
                            .addComponent(txtValidade)
                            .addComponent(txtCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQTD)
                            .addComponent(txtLucro)
                            .addComponent(txtValorCompra)
                            .addComponent(txtValorVenda)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair da tela de cadastro de produtos", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String funcao = btnSalvar.getText();
        if (funcao == "Novo") {
            btnSalvar.setText("Salvar");
            txtMarca.setEnabled(true);
            txtCategoria.setEnabled(true);
            txtValidade.setEnabled(true);
            txtQTD.setEnabled(true);
            txtValorCompra.setEnabled(true);
            txtLucro.setEnabled(true);
            txtValorVenda.setEnabled(true);
        } else {
            if (txtCategoria.getText().isEmpty() || txtLucro.getText().isEmpty() || txtMarca.getText().isEmpty()
                    || txtProduto.getText().isEmpty() || txtQTD.getText().isEmpty() || txtValidade.getText().isEmpty()
                    || txtValorCompra.getText().isEmpty() || txtValorVenda.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de salvar", "Aviso", 0);
            } else {
                produto.setNomeProduto(txtProduto.getText());
                produto.setMarcaProduto(txtMarca.getText());
                produto.setDataValidade(fd.FormataData(txtValidade.getText()));
                produto.setTipoProduto(txtCategoria.getText());
                produto.setQtdProduto(Integer.parseInt(txtQTD.getText()));
                produto.setValorCompra(Double.parseDouble(fn.ConverterFloat(txtValorCompra.getText())));
                produto.setLucroPercent(Integer.parseInt(txtLucro.getText()));
                produto.setValorVenda(Double.parseDouble(fn.ConverterFloat(txtValorVenda.getText())));
                boolean salvou = fp.CadastraProduto(produto);
                if (salvou) {
                    int mais1 = JOptionPane.showConfirmDialog(null, "Produto Salvo com sucesso", "Aviso", JOptionPane.YES_NO_OPTION);
                    if (mais1 == JOptionPane.YES_OPTION) {
                        txtCategoria.setText("");
                        txtLucro.setText("");
                        txtMarca.setText("");
                        txtProduto.setText("");
                        txtQTD.setText("");
                        txtValidade.setText("");
                        txtValorCompra.setText("");
                        txtValorVenda.setText("");
                    } else {
                        btnSalvar.setText("Novo");
                        txtMarca.setEnabled(false);
                        txtCategoria.setEnabled(false);
                        txtValidade.setEnabled(false);
                        txtQTD.setEnabled(false);
                        txtValorCompra.setEnabled(false);
                        txtLucro.setEnabled(false);
                        txtValorVenda.setEnabled(false);
                        txtCategoria.setText("");
                        txtLucro.setText("");
                        txtMarca.setText("");
                        txtProduto.setText("");
                        txtQTD.setText("");
                        txtValidade.setText("");
                        txtValorCompra.setText("");
                        txtValorVenda.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar o produto", "Aviso", 0);
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLucroFocusLost
        // TODO add your handling code here:
        String vcompra = fn.ConverterFloat(txtValorCompra.getText());
        float compra = Float.parseFloat(vcompra);
        float percento = Float.parseFloat(txtLucro.getText());
        float venda = compra + ((compra * percento) / 100);
        String valorVenda = df.format(venda);
        String valorImpresso = fn.FloatConvertido(valorVenda);
        txtValorVenda.setText(valorImpresso);
    }//GEN-LAST:event_txtLucroFocusLost

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        String funcao = btnPesquisar.getText();
        if (funcao == "Pesquisar") {
            produto = fp.BuscaProduto(txtProduto.getText());
            if (produto == null) {
                int naoEncontrado = JOptionPane.showConfirmDialog(null, "Produto não encontrado, Deseja cadastrar um novo Produto?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (naoEncontrado == JOptionPane.YES_OPTION) {
                    btnSalvar.setText("Salvar");
                    txtMarca.setEnabled(true);
                    txtCategoria.setEnabled(true);
                    txtValidade.setEnabled(true);
                    txtQTD.setEnabled(true);
                    txtValorCompra.setEnabled(true);
                    txtLucro.setEnabled(true);
                    txtValorVenda.setEnabled(true);
                }
            } else {
                txtCategoria.setText(produto.getTipoProduto());
                txtLucro.setText(Integer.toString(produto.getLucroPercent()));
                txtQTD.setText(Integer.toString(produto.getQtdProduto()));
                txtValorCompra.setText(Double.toString(produto.getValorCompra()));
                txtValorVenda.setText(Double.toString(produto.getValorVenda()));
                txtValidade.setText(fd.DataBr(produto.getDataValidade()));
                txtMarca.setText(produto.getMarcaProduto());
                btnPesquisar.setText("Atualizar");
                btnExcluir.setEnabled(true);
            }
        } else {
            produto.setNomeProduto(txtProduto.getText());
            produto.setMarcaProduto(txtMarca.getText());
            produto.setDataValidade(fd.FormataData(txtValidade.getText()));
            produto.setTipoProduto(txtCategoria.getText());
            produto.setValorCompra(Double.parseDouble(fn.ConverterFloat(txtValorCompra.getText())));
            produto.setQtdProduto(Integer.parseInt(txtQTD.getText()));
            produto.setValorVenda(Double.parseDouble(fn.ConverterFloat(txtValorVenda.getText())));
            fp.AtualizaProduto(produto);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int exclui = JOptionPane.showConfirmDialog(null, "Deseja Excluir esse produto:", "Alerta", JOptionPane.YES_NO_OPTION);
        if (exclui == JOptionPane.YES_OPTION) {
            produto = fp.BuscaProduto(txtProduto.getText());
            fp.ExcluiProduto(produto.getIdProduto());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQTD;
    private javax.swing.JFormattedTextField txtValidade;
    private javax.swing.JFormattedTextField txtValorCompra;
    private javax.swing.JFormattedTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
