/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.granpet.Telas;

import com.granpet.DAL.ModuloConector;
import com.granpet.aplicacoes.FormataData;
import com.granpet.aplicacoes.FormataNumeros;
import com.granpet.classes.Cliente;
import com.granpet.classes.ModeloTabela;
import com.granpet.funcoes.FuncoesCliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class TelaCadastraCliente extends javax.swing.JInternalFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Cliente cliente = new Cliente();
    ModeloTabela tblModelo = new ModeloTabela();
    FuncoesCliente fc = new FuncoesCliente();
    FormataNumeros fn = new FormataNumeros();
    FormataData fd = new FormataData();

    /**
     * Creates new form TelaCadastraCliente
     */
    public TelaCadastraCliente() {
        initComponents();
        conexao = ModuloConector.conector();
        if (conexao == null) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao Banco de Dados", "Atenção", 0);
        }
        //PreencherTabela();
        btnExcluir.setEnabled(false);
        btnSalvar.setText("Novo");
        txtDono.setEnabled(false);
        txtFone.setEnabled(false);
        txtDaNa.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtObs.setEnabled(false);
        txtRaca.setEnabled(false);
    }
    
    private void PreencherTabela() {
        ArrayList clientes = new ArrayList();
        String sql = "SELECT * FROM `tblcliente`";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cliente.setNomeCliente(rs.getString("nomeCliente"));
                cliente.setProprCliente(rs.getString("proprietarioCliente"));
                cliente.setFoneCliente(rs.getString("foneCliente"));
                cliente.setRacaCliente(rs.getString("racaCliente"));
                System.out.println(cliente);
                clientes.add(cliente);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro no Banco de dados " + e, "Atenção", 0);
        }
        String[] colunas = new String[]{"Nome", "Proprietario", "Telefone", "Raça"};
        System.out.println(clientes);
        tblModelo.setNcolunas(colunas.length);
        //tblClientes.setModel(mtbl);
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(160);
        tblClientes.getColumnModel().getColumn(0).setResizable(false);
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(278);
        tblClientes.getColumnModel().getColumn(1).setResizable(false);
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblClientes.getColumnModel().getColumn(2).setResizable(false);
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblClientes.getColumnModel().getColumn(3).setResizable(false);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.setAutoResizeMode(tblClientes.AUTO_RESIZE_OFF);
        //tblClientes.setSelectionModel((int)ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDono = new javax.swing.JTextField();
        txtFone = new javax.swing.JTextField();
        txtRaca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        txtDaNa = new javax.swing.JFormattedTextField();

        setResizable(true);
        setTitle("Cadastro de Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        tblClientes.setModel(tblModelo);
        jScrollPane1.setViewportView(tblClientes);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("D. N:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dono:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("OBse:");

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(89, 33));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(89, 33));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Raça:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtRaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Ender:");

        txtEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane2.setViewportView(txtObs);

        txtDaNa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDaNa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 191, Short.MAX_VALUE)
                                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jScrollPane2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(txtDaNa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRaca, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(txtFone)))
                                    .addComponent(txtEndereco)
                                    .addComponent(txtDono))))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDaNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Sair da tela de Cadastro de Cliente", "Sair", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String opcao = btnSalvar.getText();
        if (opcao == "Novo") {
            btnSalvar.setText("Salvar");
            txtDono.setEnabled(true);
            txtFone.setEnabled(true);
            txtDaNa.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtObs.setEnabled(true);
            txtRaca.setEnabled(true);
        } else {
            if (txtNome.getText().isEmpty() || txtDono.getText().isEmpty()
                    || txtFone.getText().isEmpty() || txtDaNa.getText().isEmpty()
                    || txtRaca.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtObs.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchido para salvar um novo cliente", "Aviso", 0);
            } else {
                cliente.setNomeCliente(txtNome.getText());
                cliente.setRacaCliente(txtRaca.getText());
                cliente.setProprCliente(txtDono.getText());
                cliente.setFoneCliente(txtFone.getText());
                cliente.setEnderecoCliente(txtEndereco.getText());
                cliente.setDataNascimento(fd.FormataData(txtDaNa.getText()));
                cliente.setObsCliente(txtObs.getText());
                fc.SalvaCliente(cliente);
                int cadastraNovo = JOptionPane.showConfirmDialog(null, "Cliente Cadastrado com sucesso, Deseja Cadastrar um novo Cliente?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (cadastraNovo == JOptionPane.YES_OPTION) {
                    txtNome.setText("");
                    txtDono.setText("");
                    txtFone.setText("");
                    txtDaNa.setText("");
                    txtEndereco.setText("");
                    txtRaca.setText("");
                    txtObs.setText("");
                } else {
                    btnExcluir.setEnabled(false);
                    btnSalvar.setText("Novo");
                    txtDono.setEnabled(false);
                    txtFone.setEnabled(false);
                    txtDaNa.setEnabled(false);
                    txtEndereco.setEnabled(false);
                    txtObs.setEnabled(false);
                    txtRaca.setEnabled(false);
                    txtNome.setText("");
                    txtDono.setText("");
                    txtFone.setText("");
                    txtDaNa.setText("");
                    txtEndereco.setText("");
                    txtRaca.setText("");
                    txtObs.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        cliente = fc.PesquisaCliente(txtNome.getText());
        if (btnPesquisar.getText() == "Pesquisar") {
            if (cliente == null) {
                int cadastra = JOptionPane.showConfirmDialog(null, "Cliente não encontrado, Deseja Cadastrar?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (cadastra == JOptionPane.YES_OPTION) {
                    btnSalvar.setText("Salvar");
                    txtDono.setEnabled(true);
                    txtFone.setEnabled(true);
                    txtDaNa.setEnabled(true);
                    txtEndereco.setEnabled(true);
                    txtObs.setEnabled(true);
                    txtRaca.setEnabled(true);
                }
            } else {
                txtNome.setText(cliente.getNomeCliente());
                txtDaNa.setText(fd.DataBr(cliente.getDataNascimento()));
                txtEndereco.setText(cliente.getEnderecoCliente());
                txtObs.setText(cliente.getObsCliente());
                txtDono.setText(cliente.getProprCliente());
                txtFone.setText(cliente.getFoneCliente());
                txtRaca.setText(cliente.getRacaCliente());
                btnPesquisar.setText("Atualizar");
                txtDono.setEnabled(true);
                txtFone.setEnabled(true);
                txtDaNa.setEnabled(true);
                txtEndereco.setEnabled(true);
                txtObs.setEnabled(true);
                txtRaca.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        } else {
            int atualiza = JOptionPane.showConfirmDialog(null, "Deseja atualizar os dados do Cliente", "Aviso", JOptionPane.YES_NO_OPTION);
            if (atualiza == JOptionPane.YES_OPTION) {
                cliente.setNomeCliente(txtNome.getText());
                cliente.setProprCliente(txtDono.getText());
                cliente.setRacaCliente(txtRaca.getText());
                cliente.setFoneCliente(txtFone.getText());
                fc.AtualizaCliente(cliente);
                btnExcluir.setEnabled(false);
                btnPesquisar.setText("Pesquisar");
                txtDono.setEnabled(false);
                txtFone.setEnabled(false);
                txtDaNa.setEnabled(false);
                txtEndereco.setEnabled(false);
                txtObs.setEnabled(false);
                txtRaca.setEnabled(false);
                txtNome.setText("");
                txtDono.setText("");
                txtFone.setText("");
                txtDaNa.setText("");
                txtEndereco.setText("");
                txtRaca.setText("");
                txtObs.setText("");
            } else {
                txtDono.setEnabled(true);
                txtFone.setEnabled(true);
                txtDaNa.setEnabled(true);
                txtEndereco.setEnabled(true);
                txtObs.setEnabled(true);
                txtRaca.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int excluir = JOptionPane.showConfirmDialog(null, "Deseja Excluir esse cliente", "Atenção", JOptionPane.YES_NO_OPTION);
        if (excluir == JOptionPane.YES_OPTION) {
            cliente = fc.PesquisaCliente(txtNome.getText());
            fc.ExcluiCliente(cliente.getIdCliente());
            btnExcluir.setEnabled(false);
            btnSalvar.setText("Novo");
            txtDono.setEnabled(false);
            txtFone.setEnabled(false);
            txtDaNa.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtObs.setEnabled(false);
            txtRaca.setEnabled(false);
            txtNome.setText("");
            txtDono.setText("");
            txtFone.setText("");
            txtDaNa.setText("");
            txtEndereco.setText("");
            txtRaca.setText("");
            txtObs.setText("");
            btnPesquisar.setText("Pesquisar");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField txtDaNa;
    private javax.swing.JTextField txtDono;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables
}
